package io.github.kromus.samples.prebuilt

import io.github.kromus.KeyCodec
import io.github.kromus.decodeHybridIndex
import io.github.kromus.provenanceOf
import io.github.kromus.samples.common.ToyEmbedder

/**
 * Runtime: load a prebuilt index and search it. This is all a device does.
 *
 * Note what is absent — no graph construction, no embedding of the corpus, no writer. The index is
 * read-only here, so every search can run on its own thread through `searcher()` with no lock at all.
 */
fun main() {
    val blob = checkNotNull(object {}.javaClass.getResourceAsStream("/$INDEX_RESOURCE")) {
        "index resource missing — it is generated by the buildIndex task"
    }.readBytes()

    println("loaded ${blob.size} bytes, built by '${provenanceOf(blob)}'")

    // Expecting the provenance refuses an index built with a different embedder, which would
    // otherwise return confident nonsense.
    val index = decodeHybridIndex(blob, KeyCodec.string, expect = PROVENANCE)

    val embedder = ToyEmbedder()
    val searcher = index.searcher()

    // Queries the toy embedder can actually place: each sits squarely in one of its four topics, so
    // the vector half pulls its weight and you can predict the answers by reading the lexicon.
    for (query in listOf("asynchronous code", "baking bread", "playing an instrument", "sleeping outdoors")) {
        println("\n$query")
        for (hit in searcher.search(embedder.embed(query), query, k = 3)) {
            println("  %.4f  %s".format(hit.score, hit.key))
        }
    }
}
